### PR TITLE
Add Java pre-commit hook to format code

### PR DESCRIPTION
**Pull request by dhruvi618**

### CODE REVIEW

**Comment by kmh287** [comment]
Do you want to merge this into master?

**Comment by dhruvi618** [comment]
Yes, I will be merging into master, but since the branch was created off of DhruviDev the PR included all the commits from that branch as well so I changed it to make it easier to separate the commits

**Comment by kmh287** [comment]
If we merge this PR as is, the next PR from DhruviDev into master will include these changes. What do you think about taking a new branch off of master just for these changes?

**Comment by tcwanggoogle** [comment]
Other people might benefit from merging this change to master too. Let me know if you need help offline to create a new branch off master only for this PR

**Comment by dhruvi618** [comment]
I just got approval on DhruviDev and merged it into master, so now this branch is only 1 commit ahead of master (since it was originally branched off of DhruviDev). In the future, I will definitely make sure to branch off of master to make changes, but is changing this base branch to master ok for now?

**Pull request merged**
