### PR TITLE
CSS linter: Add support to run CSS style linter during PR review

### PR DESCRIPTION
**Pull request by tcwanggoogle**

### CODE REVIEW

**Comment by kmh287** [comment]
> CSS Style Linter / stylelint (pull_request) Failing after 46s

At least we know it's working 😄

**Comment by tcwanggoogle** [comment]
The Linter will now run during PR review. The current failure is due to existing violations on master. We need a volunteer to fix this (work on linter-dev branch to push new commits here) in order for it to pass

**Comment by tcwanggoogle** [comment]
> > CSS Style Linter / stylelint (pull_request) Failing after 46s
> 
> At least we know it's working 😄

Yep, I plan to create several of these PRs to set up a linter and address the existing violations. It looks like CSS is set up now. Will try others.

**Comment by tcwanggoogle** [comment]
Should be able to submit, as the CSS linting issues are addressed. Need LGTMs

**Pull request merged**
